[package]
name = "fluency"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fy_parse = {path = "../fy_parse"}
fy_generator = {path = "../fy_generator"}

[[bin]]
name = "fluency"
